main_file: "P02home.pd"

midi_controllers:
 filter_freq: 
  midi_cc: 13
  value: 111
 filter_res: 
  midi_cc: 14
  value: 25
 preset: 
  midi_cc: 23
  value: ‘1’
  labels: [‘1’, ‘2’, ‘3’, ‘4’, ‘5’]
 glide: 
  midi_cc: 14
  value: 0
 mix_osc1: 
  midi_cc: 8
  value: 127
 mix_osc2: 
  midi_cc: 9
  value: 127
 mix_rm: 
  midi_cc: 10
  value: 0
 mix_noise: 
  midi_cc: 11
  value: 20
 lfo_speed: 
  midi_cc: 15
  value: 64
 lfo_delay:
  midi_cc: 7
  value: 16
 FFM_rate: 
  midi_cc: 1
  value: 0
 FFM_lfo:
  midi_cc: 30
  value: 0
 osc1_lfo: 
  midi_cc: 2
  value: 0
 osc1_shape: 
  midi_cc: 3
  value: 0
 osc1_semitones:
  midi_cc: 4
  value: 64
 osc1_cents:
  midi_cc: 38
  value: 64
 osc2_lfo: 
  midi_cc: 5
  value: 0
 osc2_shape: 
  midi_cc: 6
  value: 0
 osc2_semitones:
  midi_cc: 7
  value: 64
 osc2_cents:
  midi_cc: 39
  value: 64
 amp_a:
  midi_cc: 7
  value: 0
 amp_d:
  midi_cc: 7
  value: 127
 amp_s:
  midi_cc: 7
  value: 127
 amp_r:
  midi_cc: 7
  value: 64



